<a href="https://colab.research.google.com/github/PaoloBarba/ADM_HM1_Barba_1885324/blob/main/DMT2023_Lab1_SE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#INTRODUCTION

#### Information Retrieval

Information Retrieval (IR) is finding material (usually **documents**) of an unstructured nature (usually **text**) that satisfies an information need from within large collections (usually stored on computers).

#### IR is an Empirical Science

* Information Retrieval has massively benefitted from a long history of excellent test collections;

* This has allowed many retrieval models to be developed and shown their effectiveness;

* Hence, IR has been a dataset-driven empirical science for 50 years!

##PyTerrier

PyTerrier is a software framework for information retrieval experiements in Python. 

*   It embeds all the previous frameworks;
*   It allows performing experiments in a **declarative way**.

#### Installing & Configuring
Installing PyTerrier is easy - it can be installed from the command-line in the normal way using Pip: `pip install python-terrier`

All usages of PyTerrier start by importing PyTerrier and starting it using the init() method:

```
import pyterrier as pt
pt.init()
```

#### Importing Datasets
The datasets module allows easy access to existing standard test collections. In particular, each defined dataset can download and provide easy access to:
* files containing the documents of the corpus
* topics (queries), as a dataframe, ready for retrieval
* relevance assessments (aka, labels or qrels), as a dataframe, ready for evaluation
* ready-made Terrier indices, where appropriate

#### Indexing
PyTerrier has a number of useful classes for creating Terrier indices, which can be used for retrieval, query expansion, etc. There are four indexer classes:

* You can create an index from TREC-formatted files, from a TREC test collection, using TRECCollectionIndexer.
* You can use FilesIndexer for indexing TXT, PDF, Microsoft Word files, etc.
* For indexing Pandas Dataframe you can use DFIndexer.
* For any **abitrary iterable dictionaries**, you can use IterDictIndexer.

#### Terrier Retrieval
**BatchRetrieve** is one of the most commonly used PyTerrier objects. It represents a retrieval transformation, in which queries are mapped to retrieved documents. BatchRetrieve uses a pre-existing Terrier index data structure, typically saved on disk.

#CODE

## Libraries

> We need to install **PyTerrier** as it is not part of Python standard libraries

In [1]:
pip install python-terrier

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting python-terrier
  Downloading python-terrier-0.9.2.tar.gz (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.4/104.4 KB 3.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from python-terrier) (1.22.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from python-terrier) (1.3.5)
Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from python-terrier) (4.64.1)
Collecting pyjnius>=1.4.2
  Downloading pyjnius-1.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 44.3 MB/s eta 0:00:00
Collecting matchpy
  Downloading matchpy-0.5.5-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.6/69.6 KB 3.3 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.8/dist-packages (from python-terrier) (1.2.1)
Collecting deprecated
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting chest
  Downloading chest-0.2.3.tar.gz (9.6 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from python-terrier) (1.10.1)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from python-terrier) (2.25.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from python-terrier) (1.2.0)
Collecting nptyping==1.4.4
  Downloading nptyping-1.4.4-py3-none-any.whl (31 kB)
Requirement already satisfied: more_itertools in /usr/local/lib/python3.8/dist-packages (from python-terrier) (9.1.0)
Collecting ir_datasets>=0.3.2
  Downloading ir_datasets-0.5.4-py3-none-any.whl (311 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.5/311.5 KB 16.7 MB/s eta 0:00:00
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/dist-packages (from python-terrier) (3.1.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.8/dist-packages (from python-terrier) (0.13.5)
Collecting ir_measures>=0.3.1
  Downloading ir_measures-0.3.1.tar.gz (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.5/46.5 KB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting dill
  Downloading dill-0.3.6-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 7.4 MB/s eta 0:00:00
Collecting pytrec_eval_terrier>=0.5.3
  Downloading pytrec_eval_terrier-0.5.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (286 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 286.6/286.6 KB 19.2 MB/s eta 0:00:00
Collecting typish>=1.7.0
  Downloading typish-1.9.3-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.1/45.1 KB 1.0 MB/s eta 0:00:00
Collecting warc3-wet>=0.2.3
  Downloading warc3_wet-0.2.3-py3-none-any.whl (13 kB)
Collecting trec-car-tools>=2.5.4
  Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Collecting zlib-state>=0.1.3
  Downloading zlib_state-0.1.5-cp38-cp38-manylinux2010_x86_64.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.6/72.6 KB 3.9 MB/s eta 0:00:00
Collecting unlzw3>=0.2.1
  Downloading unlzw3-0.2.2-py3-none-any.whl (6.1 kB)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.8/dist-packages (from ir_datasets>=0.3.2->python-terrier) (4.6.3)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.8/dist-packages (from ir_datasets>=0.3.2->python-terrier) (6.0)
Collecting lz4>=3.1.1
  Downloading lz4-4.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 21.8 MB/s eta 0:00:00
Collecting pyautocorpus>=0.1.1
  Downloading pyautocorpus-0.1.9-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (293 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.0/293.0 KB 14.9 MB/s eta 0:00:00
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.8/dist-packages (from ir_datasets>=0.3.2->python-terrier) (4.9.2)
Collecting ijson>=3.1.3
  Downloading ijson-3.2.0.post0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.8/114.8 KB 4.7 MB/s eta 0:00:00
Collecting warc3-wet-clueweb09>=0.2.5
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting cwl-eval>=1.0.10
  Downloading cwl-eval-1.0.12.tar.gz (31 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.8/dist-packages (from pyjnius>=1.4.2->python-terrier) (1.15.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->python-terrier) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->python-terrier) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->python-terrier) (1.26.14)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->python-terrier) (2.10)
Requirement already satisfied: heapdict in /usr/local/lib/python3.8/dist-packages (from chest->python-terrier) (1.0.1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.8/dist-packages (from deprecated->python-terrier) (1.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from jinja2->python-terrier) (2.1.2)
Collecting multiset<3.0,>=2.0
  Downloading multiset-2.1.1-py2.py3-none-any.whl (8.8 kB)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->python-terrier) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->python-terrier) (2.8.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn->python-terrier) (3.1.0)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.8/dist-packages (from statsmodels->python-terrier) (0.5.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.8/dist-packages (from statsmodels->python-terrier) (23.0)
Collecting cbor>=1.0.0
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: python-terrier, ir_measures, chest, wget, cwl-eval, warc3-wet-clueweb09, cbor
  Building wheel for python-terrier (setup.py) ... done
  Created wheel for python-terrier: filename=python_terrier-0.9.2-py3-none-any.whl size=112280 sha256=a448487fbea6f8b3fcbc388d283750a8529b34962f2c56e681f4a2d49c82c89a
  Stored in directory: /root/.cache/pip/wheels/3a/16/35/b887bda339a940232814f8f2a265b47ccb552b2656e9894985
  Building wheel for ir_measures (setup.py) ... done
  Created wheel for ir_measures: filename=ir_measures-0.3.1-py3-none-any.whl size=60192 sha256=aeb37a88a7e0c0b24ef4e2fe51939581f47b6cb1d1352426e115e2d76c74eb1b
  Stored in directory: /root/.cache/pip/wheels/e0/62/25/77a51a011fc5c0a771372e08914c2d7451b3e76114a1067358
  Building wheel for chest (setup.py) ... done
  Created wheel for chest: filename=chest-0.2.3-py3-none-any.whl size=7633 sha256=9c3ca32b9d41116ef66721919a3830634daf335fd6fd9e9369d351b43903cdd1
  Stored in directory: /root/.cache/pip/wheels/a3/10/0c/3c77925ea9d4deccf5e0a06a27a2c4cea4464bb57d68015eba
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9674 sha256=b8dd96b15ae257c8497dd44da9aed3869ce693f38f68426bcf56446e51f18c01
  Stored in directory: /root/.cache/pip/wheels/bd/a8/c3/3cf2c14a1837a4e04bd98631724e81f33f462d86a1d895fae0
  Building wheel for cwl-eval (setup.py) ... done
  Created wheel for cwl-eval: filename=cwl_eval-1.0.12-py3-none-any.whl size=38085 sha256=4c14433f4d00fdf26d930c380df1b68690cfa2711c546ff53bb1c5e4a0b26df7
  Stored in directory: /root/.cache/pip/wheels/6f/20/44/7bd8b3e175eb9d1343f1668f7d57e36f1a9fcb74ef7cd269ed
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18920 sha256=4f83e8c27f5892a1dd7187bd16871a267e2937c5413509927658c34d75bd5d53
  Stored in directory: /root/.cache/pip/wheels/2f/81/96/219c1a4ebbcb766834ccef089c56481b761c26d8ed235e21dc
  Building wheel for cbor (setup.py) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp38-cp38-linux_x86_64.whl size=57904 sha256=2ab3e2f82feb9457dd26c8b1e48e9b297e5a60531f0ff782f2256f6dff42287e
  Stored in directory: /root/.cache/pip/wheels/31/3a/8a/9d1a5e6f83f620826578089812b8ac236b86eaf4fbc3b36384
Successfully built python-terrier ir_measures chest wget cwl-eval warc3-wet-clueweb09 cbor
Installing collected packages: wget, warc3-wet-clueweb09, warc3-wet, typish, multiset, ijson, cbor, zlib-state, unlzw3, trec-car-tools, pytrec_eval_terrier, pyjnius, pyautocorpus, nptyping, matchpy, lz4, dill, deprecated, cwl-eval, chest, ir_measures, ir_datasets, python-terrier
Successfully installed cbor-1.0.0 chest-0.2.3 cwl-eval-1.0.12 deprecated-1.2.13 dill-0.3.6 ijson-3.2.0.post0 ir_datasets-0.5.4 ir_measures-0.3.1 lz4-4.3.2 matchpy-0.5.5 multiset-2.1.1 nptyping-1.4.4 pyautocorpus-0.1.9 pyjnius-1.4.2 python-terrier-0.9.2 pytrec_eval_terrier-0.5.5 trec-car-tools-2.6 typish-1.9.3 unlzw3-0.2.2 warc3-wet-0.2.3 warc3-wet-clueweb09-0.2.5 wget-3.2 zlib-state-0.1.5

> Now we can import **PyTerrier**

In [2]:
import pyterrier as pt

> We also need to import the **pandas** library to handle DataFrames

In [3]:
import pandas as pd

In [5]:
import logging, sys
logging.disable(sys.maxsize)

### Initialization
> It is necessary to call the PyTerrier `init` function before Terrier classes and methods can be used. This function imports classes and also finds the correct version of Terrier to download if no version is specified.

> This is a peculiarity of PyTerrier and is not necessary for the other libraries we need.

In [6]:
if not pt.started():
  pt.init()

> The `started` method of the PyTerrier package returns *True* if `init()` has already been called, `False` otherwise.

###Custom functions
Here are hidden imports and custom functions defined to simplify certain steps or improve certain visual outputs.

In [ ]:
from IPython.display import display, display_html

In [ ]:
def format_query_result(results, df, field):
  merged_df = pd.merge(results, df, left_on='docno', right_on='docno') #merge the two dfs

  merged_df = merged_df.loc[:, ["rank", "score", *field]] #subset to columns we are interested in
  
  return merged_df

In [ ]:
def display_query_result(results_dict, df):
  for field,results in results_dict.items():
    previous_max_col_width = pd.options.display.max_colwidth #save current max_col_width
    pd.options.display.max_colwidth = 1000 #change max_colwidth to display more text
    
    merged_df = format_query_result(results,df,field) #get formatted results
    
    display(merged_df) #display result

    pd.options.display.max_colwidth = previous_max_col_width #reset previous max_col_width

In [ ]:
def display_matrix_results(results_dict):
  df_stylers = []
  for i,(k,v) in enumerate(results_dict.items()):
    if k[0]=="":
      app = "No preprocessing"
    else:
      app = k[0]
    df_stylers.append(v.style.format(formatter={("score"): "{:.1f}", ("text"): "{:.70}"}).set_table_attributes("style='display:inline'").set_caption(app+" with "+k[1]))

  app = df_stylers[0]._repr_html_()
  for i,df_styler in enumerate(df_stylers[1:]):
    if i%2==1:
      app += "<br>" + "-"*230 + "\n"
    app += df_styler._repr_html_()
  display_html(app, raw=True)

## Custom Dataset

### Data

> Here we define an illustrative dataframe on which to perform queries

In [ ]:
df = pd.DataFrame({
  'docno':
    ['98', '81', '63', '59', '53', '65', '75', '45'],
    'title':
    ["Bank of Italy",
     "List of italian banks", 
     "Zoology class",
     "History of banking",
     "Title",
     "History of banking",
     "Spam document",
     "History of banking"
    ],
  'text':
    ["The Bank of Italy is the central bank of Italy and part of the European System of Central Banks.",
     "List of italian banks", 
     "History of animals that lived near banks of rivers",
     "Many of histories position the development of a banking system to medieval and Renaissance Italy",
     "History of banking",
     "History of banking: the development of the banking system...",
     "Of of of of of of of of of of of of of of of of apple",
     "spam apple of spam of spam bank spam spam history spam Sony spam spam soccer spam cinema spam spam sales spam buy spam spam TV spam offer spam job work spam Pokémon spam"
    ]
  })

In [ ]:
df

,docno,title,text
0,98,Bank of Italy,The Bank of Italy is the central bank of Italy...
1,81,List of italian banks,List of italian banks
2,63,Zoology class,History of animals that lived near banks of ri...
3,59,History of banking,Many of histories position the development of ...
4,53,Title,History of banking
5,65,History of banking,History of banking: the development of the ban...
6,75,Spam document,Of of of of of of of of of of of of of of of o...
7,45,History of banking,spam apple of spam of spam bank spam spam hist...

### Indexing

> To create the index used to perform the queries, we must follow these steps:
1. Initialize a **DFIndexer** object, specifying in which folder to put the index
>> We also specify that we want to *overwrite* the index, if found.
2. Set a **preprocessing** configuration.
3. Pass the *text* and *docno* **fields** to the indexer

---

> We create a **function** that takes as argument a *preprocessing_configuration* string, as we want to **repeat** the index creation for various configurations, and returns the computed index. The *field* to be indexed is also an input variable (it will become clear later why).

In [ ]:
def create_index(preprocessing_configuration, field):
  pd_indexer = pt.DFIndexer("./Inverted_Index", overwrite=True)
  
  pd_indexer.setProperty("termpipelines", preprocessing_configuration)
  
  indexref = pd_indexer.index(df[field], df["docno"])

  return indexref

###Querying

> After the index creation, we'll need to specify a **weighting model** (a.k.a. **scoring function**) to compute the score of a document given a query.

> As before, here we define a function that takes as input the previously initialized index and the name of the weighting model and returns the **retrieval model**.

In [ ]:
def create_retrieval_model(indexref, scoring_function):
  return pt.BatchRetrieve(indexref, wmodel = scoring_function)

> **The retrieval model will take as input a query and return its result**.

### First Example

> First of all, we need to call the functions that we have just defined and create the index and the retrieval model

---

> To begin with, let's not use any **pre-processing** for the **index**

In [ ]:
indexref = create_index(preprocessing_configuration = "", field = "text")

<ipython-input-7-d00ae2495210>:6: DeprecationWarning: Setting of termpipelines property directly is deprecated
  indexref = pd_indexer.index(df[field], df["docno"])

> For the scoring function, let's use **CoordinateMatch**.

> We must also remember to feed the *indexref* to the `create_retrieval_model` function

In [ ]:
terms_presence_nopreproc = create_retrieval_model(indexref, scoring_function = "CoordinateMatch")

> Now we are ready to perform our **query**. Let's assume we want to find out articles about the *History of banking*

In [ ]:
query = "History of banking"
results = terms_presence_nopreproc.search(query)

> Let's visualize the results

In [ ]:
results

  qid  docid docno  rank  score               query
0   1      4    53     0    3.0  History of banking
1   1      5    65     1    3.0  History of banking
2   1      2    63     2    2.0  History of banking
3   1      3    59     3    2.0  History of banking
4   1      7    45     4    2.0  History of banking
5   1      0    98     5    1.0  History of banking
6   1      1    81     6    1.0  History of banking
7   1      6    75     7    1.0  History of banking

> Since this is not much informative, let's add to each row the text corresponding to the document number (*docno*). We'll use a custom printing function defined earlier.

In [ ]:
display_query_result({("text",):results},df)
#YOUR TURN: Try to alter the Pandas DataFrame to see the effect in the output and try to predict it

,rank,score,text
0,0,3.0,History of banking
1,1,3.0,History of banking: the development of the banking system...
2,2,2.0,History of animals that lived near banks of rivers
3,3,2.0,Many of histories position the development of a banking system to medieval and Renaissance Italy
4,4,2.0,spam apple of spam of spam bank spam spam history spam Sony spam spam soccer spam cinema spam spam sales spam buy spam spam TV spam offer spam job work spam Pokémon spam
5,5,1.0,The Bank of Italy is the central bank of Italy and part of the European System of Central Banks.
6,6,1.0,List of italian banks
7,7,1.0,Of of of of of of of of of of of of of of of of apple

### More rigorous tests

> Now that we have understood how to initialise an index, create a retrieval model and make a query, let's try to see what changes depending on the preprocessing used and the scoring function chosen.

In [ ]:
possible_preprocessing = ["", #no preprocessing
                          "Stopwords", #remove stopwords
                          "EnglishSnowballStemmer", #Probably the most famous stemmer in the world
                          "Stopwords, EnglishSnowballStemmer"] #Both previous ones

possible_wmodels = ["CoordinateMatch", #Term presence
                    "Tf"] #Term frequency

#YOUR TURN: Try to change preprocessing and/or scoring function; use PyTerrier documentation for reference.

> Let us now build a program that tries every possible **combination of preprocessing configuration and scoring function**, and then we can check the difference in the results.

> The query will always be `"History of banking"`.

> A python `dict` will be used to save the results for each combination of preprocessing and scoring function.

In [ ]:
query = "History of banking"
results_dict = {}
for preprocessing_configuration in possible_preprocessing:
  indexref = create_index(preprocessing_configuration, "text")
  for wmodel in possible_wmodels:
    retrieval_model = create_retrieval_model(indexref, wmodel)
    results = retrieval_model.search(query)

    results_dict[(preprocessing_configuration, wmodel)] = format_query_result(results,df,("text",))

<ipython-input-7-d00ae2495210>:6: DeprecationWarning: Setting of termpipelines property directly is deprecated
  indexref = pd_indexer.index(df[field], df["docno"])

> Now, using a custom function, we will show all the results in a matrix fashion to highlight the differences between the different configurations.

In [ ]:
display_matrix_results(results_dict)

,rank,score,text
0,0,3.0,History of banking
1,1,3.0,History of banking: the development of the banking system...
2,2,2.0,History of animals that lived near banks of rivers
3,3,2.0,Many of histories position the development of a banking system to medi
4,4,2.0,spam apple of spam of spam bank spam spam history spam Sony spam spam
5,5,1.0,The Bank of Italy is the central bank of Italy and part of the Europea
6,6,1.0,List of italian banks
7,7,1.0,Of of of of of of of of of of of of of of of of apple
,rank,score,text
0,0,16.0,Of of of of of of of of of of of of of of of of apple
1,1,5.0,History of banking: the development of the banking system...
2,2,4.0,The Bank of Italy is the central bank of Italy and part of the Europea
3,3,3.0,History of animals that lived near banks of rivers
4,4,3.0,Many of histories position the development of a banking system to medi
5,5,3.0,History of banking
6,6,3.0,spam apple of spam of spam bank spam spam history spam Sony spam spam
7,7,1.0,List of italian banks
,rank,score,text
0,0,2.0,History of banking
1,1,2.0,History of banking: the development of the banking system...
2,2,1.0,History of animals that lived near banks of rivers
3,3,1.0,Many of histories position the development of a banking system to medi
4,4,1.0,spam apple of spam of spam bank spam spam history spam Sony spam spam
,rank,score,text
0,0,3.0,History of banking: the development of the banking system...
1,1,2.0,History of banking
2,2,1.0,History of animals that lived near banks of rivers
3,3,1.0,Many of histories position the development of a banking system to medi
4,4,1.0,spam apple of spam of spam bank spam spam history spam Sony spam spam
,rank,score,text
0,0,3.0,History of animals that lived near banks of rivers
1,1,3.0,Many of histories position the development of a banking system to medi
2,2,3.0,History of banking
3,3,3.0,History of banking: the development of the banking system...
4,4,3.0,spam apple of spam of spam bank spam spam history spam Sony spam spam
5,5,2.0,The Bank of Italy is the central bank of Italy and part of the Europea
6,6,2.0,List of italian banks
7,7,1.0,Of of of of of of of of of of of of of of of of apple
,rank,score,text
0,0,16.0,Of of of of of of of of of of of of of of of of apple
1,1,7.0,The Bank of Italy is the central bank of Italy and part of the Europea
2,2,5.0,History of banking: the development of the banking system...
3,3,4.0,History of animals that lived near banks of rivers
4,4,4.0,Many of histories position the development of a banking system to medi
5,5,4.0,spam apple of spam of spam bank spam spam history spam Sony spam spam
6,6,3.0,History of banking
7,7,2.0,List of italian banks
,rank,score,text
0,0,2.0,History of animals that lived near banks of rivers
1,1,2.0,Many of histories position the development of a banking system to medi
2,2,2.0,History of banking
3,3,2.0,History of banking: the development of the banking system...
4,4,2.0,spam apple of spam of spam bank spam spam history spam Sony spam spam
5,5,1.0,The Bank of Italy is the central bank of Italy and part of the Europea
6,6,1.0,List of italian banks
,rank,score,text
0,0,3.0,The Bank of Italy is the central bank of Italy and part of the Europea
1,1,3.0,History of banking: the development of the banking system...
2,2,2.0,History of animals that lived near banks of rivers
3,3,2.0,Many of histories position the development of a banking system to medi
4,4,2.0,History of banking
5,5,2.0,spam apple of spam of spam bank spam spam history spam Sony spam spam
6,6,1.0,List of italian banks

### Indexing different fields

> Using the functions created earlier, we build the index and the resulting retrieval model for the *text* and *title* fields

In [ ]:
text_indexref = create_index("Stopwords, EnglishSnowballStemmer","text")
text_retr_model = create_retrieval_model(text_indexref, "Tf")

title_indexref = create_index("Stopwords, EnglishSnowballStemmer","title")
title_retr_model = create_retrieval_model(title_indexref, "CoordinateMatch")

<ipython-input-7-d00ae2495210>:6: DeprecationWarning: Setting of termpipelines property directly is deprecated
  indexref = pd_indexer.index(df[field], df["docno"])

> Now, we can get the results for the same query (*History of banking*) on **different** fields

In [ ]:
query = "History of Banking"

results_text = format_query_result(text_retr_model.search(query),df,("docid","title","text"))
results_title = format_query_result(title_retr_model.search(query),df,("docid","title","text"))

In [ ]:
results_text

,rank,score,docid,title,text
0,0,3.0,0,Bank of Italy,The Bank of Italy is the central bank of Italy...
1,1,3.0,5,History of banking,History of banking: the development of the ban...
2,2,2.0,2,Zoology class,History of animals that lived near banks of ri...
3,3,2.0,3,History of banking,Many of histories position the development of ...
4,4,2.0,4,Title,History of banking
5,5,2.0,7,History of banking,spam apple of spam of spam bank spam spam hist...
6,6,1.0,1,List of italian banks,List of italian banks

In [ ]:
results_title

,rank,score,docid,title,text
0,0,2.0,3,History of banking,Many of histories position the development of ...
1,1,2.0,5,History of banking,History of banking: the development of the ban...
2,2,2.0,7,History of banking,spam apple of spam of spam bank spam spam hist...
3,3,1.0,0,Bank of Italy,The Bank of Italy is the central bank of Italy...
4,4,1.0,1,List of italian banks,List of italian banks

## Indexing file

> We can also try to index data not within PyTerrier but personal txt files.

> As an example, we will stream the collection of tweets "Democrat vs. Republican Tweets" obtained from Kaggle. It is formatted as "[docno] \t [text] \n". We have stored this data on the web for everyone to access.

> The data is in our shared Drive folder, in the data subfolder. To upload the file to this machine, we need to use the gdown command. We will see this command in more detail in the next sessions.

In [ ]:
!gdown 12z4xEGPcenFhQm5BA4dFJkE8EIVdAssn

Downloading...
From: https://drive.google.com/uc?id=12z4xEGPcenFhQm5BA4dFJkE8EIVdAssn
To: /content/tweets.txt
100% 12.4M/12.4M [00:00<00:00, 245MB/s]

> The `tweet_doc_iter` function will download the data from the specified url or file and return a python iterable in the form of a dict.

In [ ]:
df = []
with open("tweets.txt","r") as f:
  for i, line in enumerate(f):
    if i % 1000 == 0:
        print(f'processing document {i}')
    record = line.strip().split('\t')
    if len(record) < 2:
      print(record)
      continue
    docno, text = record[0], record[1] 
    df.append({'docno': docno, 'text': text})
df = pd.DataFrame(df).set_index("docno",drop=False) #drop=False to keep the "docno" column

processing document 0
processing document 1000
processing document 2000
processing document 3000
processing document 4000
processing document 5000
processing document 6000
processing document 7000
processing document 8000
processing document 9000
processing document 10000
processing document 11000
processing document 12000
processing document 13000
processing document 14000
processing document 15000
processing document 16000
processing document 17000
processing document 18000
processing document 19000
processing document 20000
processing document 21000
processing document 22000
processing document 23000
processing document 24000
processing document 25000
processing document 26000
processing document 27000
processing document 28000
processing document 29000
processing document 30000
processing document 31000
processing document 32000
processing document 33000
processing document 34000
processing document 35000
processing document 36000
processing document 37000
processing document 38000
processing document 39000
processing document 40000
processing document 41000
processing document 42000
processing document 43000
processing document 44000
processing document 45000
processing document 46000
processing document 47000
processing document 48000
processing document 49000
processing document 50000
processing document 51000
processing document 52000
processing document 53000
processing document 54000
processing document 55000
processing document 56000
processing document 57000
processing document 58000
processing document 59000
processing document 60000
processing document 61000
processing document 62000
processing document 63000
processing document 64000
processing document 65000
processing document 66000
processing document 67000
processing document 68000
processing document 69000
processing document 70000
processing document 71000
processing document 72000
processing document 73000
processing document 74000
processing document 75000
processing document 76000
processing document 77000
processing document 78000
processing document 79000
processing document 80000
processing document 81000
processing document 82000
processing document 83000
processing document 84000
processing document 85000
processing document 86000

In [ ]:
def tweet_doc_iter_from_file(df):
  for row in df.to_dict("records"):
    yield row

In [ ]:
folder_pos = "./iter_index"

!rm -r $folder_pos #remove index if already created

rm: cannot remove './iter_index': No such file or directory

In [ ]:
indexer = pt.IterDictIndexer(folder_pos, blocks=True)

doc_iter = tweet_doc_iter_from_file(df)
index3 = indexer.index(doc_iter, meta=['docno', 'text'])

<ipython-input-32-5d7e90eead84>:4: DeprecationWarning: specifying meta and meta_lengths in IterDictIndexer.index() is deprecated, use constructor instead
  index3 = indexer.index(doc_iter, meta=['docno', 'text'])

16:26:18.359 [ForkJoinPool-1-worker-3] WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (9132) - further warnings are suppressed
16:26:41.281 [ForkJoinPool-1-worker-3] WARN org.terrier.structures.indexing.Indexer - Indexed 2 empty documents

> As we can see, the `IterDictIndexer` object can index any iterable type

In [ ]:
index_factory = pt.IndexFactory.of(index3)
print(index_factory.getCollectionStatistics().toString())

Number of documents: 86460
Number of terms: 113652
Number of postings: 1043269
Number of fields: 1
Number of tokens: 1064228
Field names: [text]
Positions:   true

In [ ]:
tf = pt.BatchRetrieve(index3, wmodel="Tf", metadata=["docno", "text"])

retrieval_model = tf % 10

In [ ]:
retrieval_model.search("bitcoin")

,qid,docid,docno,text,rank,score,query
0,1,33335,33335,"Just like stock trades or financial assets, me...",0,1.0,bitcoin
1,1,33339,33339,The buying &amp; selling of #bitcoins &amp; ot...,1,1.0,bitcoin
2,1,50228,50228,We are discussing the challenges and opportuni...,2,1.0,bitcoin
3,1,70120,70120,RT @FortuneMagazine: Tax bill calls for bitcoi...,3,1.0,bitcoin
4,1,70121,70121,RT @SiliconANGLE: New law would introduce capi...,4,1.0,bitcoin
5,1,74245,74245,RT @RepLoudermilk: We are discussing the chall...,5,1.0,bitcoin
6,1,75811,75811,RT @listendestro: @realDonaldTrump Bitcoin rules.,6,1.0,bitcoin
7,1,84786,84786,RT @HouseScience: WATCH LIVE: Beyond #Bitcoin:...,7,1.0,bitcoin

In [ ]:
retrieval_model.search("money laundering")

,qid,docid,docno,text,rank,score,query
0,1,29094,29094,RT @RepTedDeutch: If youre a lobbyist who neve...,0,2.0,money laundering
1,1,29098,29098,"If youre a lobbyist who never gave us money, I...",1,2.0,money laundering
2,1,29247,29247,#Backpage.com CEO Carl Ferrer has pled guilty ...,2,2.0,money laundering
3,1,36277,36277,RT @OTLonESPN: For the leagues to expect any ...,3,2.0,money laundering
4,1,39028,39028,8 yrs ago #CitizensUnited opened the floodgate...,4,2.0,money laundering
5,1,39720,39720,The Mueller files and other documents suggest ...,5,2.0,money laundering
6,1,42835,42835,".@PPAdvocatesINKY, you know full well that mon...",6,2.0,money laundering
7,1,46846,46846,"Tonight, the House will pass the End Banking f...",7,2.0,money laundering
8,1,56161,56161,#PrisonReform is a money and a moral issueIt's...,8,2.0,money laundering
9,1,59697,59697,RT @WaysandMeansGOP: Because we are not talki...,9,2.0,money laundering

In [ ]:
retrieval_model.search("Clinton")

,qid,docid,docno,text,rank,score,query
0,1,17029,17029,Russian Spies met w/ Trump Campaign. To discus...,0,2.0,Clinton
1,1,86442,86442,We need answers now. We must investigate Clint...,1,2.0,Clinton
2,1,5416,5416,RT @DeanObeidallah: I agree 100% with Rudy Giu...,2,1.0,Clinton
3,1,9569,9569,"RT @JohnBrennan: I served 6 Presidents, 3 Rs &...",3,1.0,Clinton
4,1,19038,19038,RT @InvestigateRU: .@RepSarbanes: Trump campai...,4,1.0,Clinton
5,1,25364,25364,RT @RepAdamSchiff: Russian social media campai...,5,1.0,Clinton
6,1,27303,27303,RT @KellyannePolls: Astonished by the all-out ...,6,1.0,Clinton
7,1,28372,28372,"Background checks save lives. 24 years ago, Pr...",7,1.0,Clinton
8,1,28818,28818,Virtually every Clinton-related matter that Pr...,8,1.0,Clinton
9,1,29586,29586,I added a video to a @YouTube playlist http://...,9,1.0,Clinton

## PyTerrier Datasets

> The datasets module allows easy access to existing standard test collections. In particular, each defined dataset can download and provide easy access to:
* files containing the documents of the corpus,
* topics (**queries**), as a dataframe, ready for retrieval,
* relevance assessments (aka, labels or qrels), as a dataframe, ready for evaluation: the **ground truth**.

In [ ]:
terrier_datasets = pt.datasets.list_datasets()

> Let's have a brief look at the list of datasets provided by the PyTerrier library

In [ ]:
terrier_datasets

,dataset,topics,topics_lang,qrels,corpus,corpus_lang,index,info_url
0,50pct,"[training, validation]",en,"[training, validation]",None,None,"[ex2, ex3]",None
1,antique,"[train, test]",en,"[train, test]",True,en,None,https://ciir.cs.umass.edu/downloads/Antique/re...
2,vaswani,True,en,True,True,en,True,http://ir.dcs.gla.ac.uk/resources/test_collect...
3,msmarco_document,"[train, dev, test, test-2020, leaderboard-2020]",en,"[train, dev, test, test-2020]",True,en,True,https://microsoft.github.io/msmarco/
4,msmarcov2_document,"[train, dev1, dev2, valid1, valid2, trec_2021]",en,"[train, dev1, dev2, valid1, valid2]",None,None,True,https://microsoft.github.io/msmarco/TREC-Deep-...
...,...,...,...,...,...,...,...,...
641,irds:hc4,None,None,None,None,None,None,https://ir-datasets.com/hc4.html
654,irds:neuclir,None,None,None,None,None,None,https://ir-datasets.com/neuclir.html
655,irds:neuclir/1,None,None,None,None,None,None,https://ir-datasets.com/neuclir.html#neuclir/1
662,trec-deep-learning-docs,"[train, dev, test, test-2020, leaderboard-2020]",en,"[train, dev, test, test-2020]",True,en,True,https://microsoft.github.io/msmarco/
663,trec-deep-learning-passages,"[train, dev, dev.small, eval, eval.small, test...",en,"[train, dev, test-2019, test-2020, dev.small]",True,en,True,https://microsoft.github.io/MSMARCO-Passage-Ra...

### Indexing

> The dataset we will use is the one called Covid, which is part of the TREC (Text REtrieval Conference) collection. This is a collection of biomedical literature articles of COVID-related topics.
> Each document contains title, abstract, doi and date.

> After defining the dataset name, we download the dataset using the command `pt.get_dataset`

In [ ]:
dataset_name = 'irds:cord19/trec-covid'

dataset = pt.get_dataset(dataset_name) #download dataset

> First we define the folder where to put the index.

> We also remove the folder in case it has already been created. This command may be commented if we want to keep an already built index.

In [ ]:
folder_pos = './irds:cord19/trec-covid/'

!rm -r $folder_pos #remove index if already created

> We create the indexer using the `IterDictIndexer` method. We need to specify the folder path. We also specify `meta_reverse = []`, that defaults to *docno*; this represents what metadata should we be able to resolve back to a *docid*. If there are two documents with the same docno (as we know they are in this case), not specifying it will lead to an error in index creation.

> The indexer is now ready to index the dataset, that is passed to it using the `get_corpus_iter` method. We specify also the `fields` to index, *abstract* and *title*, and the `meta` data we want to retrieve from each query. We have added *title* and *abstract* just to have a more informative query result, but normally you only need the `docno`.

In [ ]:
indexer = pt.IterDictIndexer(folder_pos,  meta_reverse = [], blocks = True)
index1 = indexer.index(dataset.get_corpus_iter(), fields=('abstract','title'), meta=('docno','title','abstract'))

[INFO] [starting] building docstore
[INFO] If you have a local copy of https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/80d664e496b8b7e50a39c6f6bb92e0ef
[INFO] [starting] https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv
docs_iter:   0%|                                    | 0/192509 [00:00<?, ?doc/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.0%| 0.00/269M [00:00<?, ?B/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.0%| 115k/269M [00:00<04:00, 1.12MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 0.4%| 1.16M/269M [00:00<00:50, 5.27MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 2.5%| 6.69M/269M [00:00<00:12, 20.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 4.8%| 12.9M/269M [00:00<00:08, 30.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 7.4%| 19.9M/269M [00:00<00:06, 38.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 10.0%| 26.9M/269M [00:00<00:05, 40.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 12.6%| 34.0M/269M [00:00<00:06, 38.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 15.2%| 41.0M/269M [00:01<00:05, 40.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 17.8%| 48.0M/269M [00:01<00:05, 42.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 20.4%| 55.0M/269M [00:01<00:04, 43.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 23.0%| 62.0M/269M [00:01<00:04, 44.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 25.6%| 69.0M/269M [00:01<00:04, 45.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 28.2%| 76.0M/269M [00:01<00:04, 45.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 30.8%| 83.0M/269M [00:01<00:03, 46.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 33.5%| 90.1M/269M [00:01<00:03, 48.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 36.1%| 97.1M/269M [00:02<00:03, 44.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 38.7%| 104M/269M [00:02<00:03, 44.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 41.3%| 111M/269M [00:02<00:03, 44.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 43.9%| 118M/269M [00:02<00:03, 44.5MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 46.5%| 125M/269M [00:02<00:03, 45.0MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 49.1%| 132M/269M [00:02<00:03, 45.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 51.7%| 139M/269M [00:03<00:02, 45.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 54.3%| 146M/269M [00:03<00:02, 45.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 56.9%| 153M/269M [00:03<00:02, 42.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 59.5%| 160M/269M [00:03<00:02, 43.1MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 62.1%| 167M/269M [00:03<00:02, 43.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 64.7%| 174M/269M [00:03<00:02, 44.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 67.3%| 181M/269M [00:04<00:01, 44.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 69.9%| 188M/269M [00:04<00:01, 44.3MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 72.5%| 195M/269M [00:04<00:01, 44.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 75.1%| 202M/269M [00:04<00:01, 43.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 77.7%| 209M/269M [00:04<00:01, 44.2MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 80.3%| 216M/269M [00:04<00:01, 44.7MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 82.9%| 223M/269M [00:05<00:01, 44.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 85.5%| 230M/269M [00:05<00:00, 44.4MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 88.1%| 237M/269M [00:05<00:00, 44.8MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 90.8%| 244M/269M [00:05<00:00, 44.6MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 93.4%| 251M/269M [00:05<00:00, 44.9MB/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: 96.0%| 258M/269M [00:05<00:00, 44.8MB/s]

[INFO] [finished] https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: [00:06] [269MB] [44.6MB/s]
docs_iter:   0%|                                    | 0/192509 [00:06<?, ?doc/s]
https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/2020-07-16/metadata.csv: [00:06] [269MB] [44.5MB/s]
docs_iter: 100%|█████████████████████| 192509/192509 [00:22<00:00, 8641.52doc/s]
[INFO] [finished] docs_iter: [00:22] [192509doc] [8640.91doc/s]
[INFO] [finished] building docstore [22.29s]

cord19/trec-covid documents:   0%|          | 0/192509 [00:00<?, ?it/s]

<ipython-input-43-882ae1896157>:2: DeprecationWarning: specifying meta and meta_lengths in IterDictIndexer.index() is deprecated, use constructor instead
  index1 = indexer.index(dataset.get_corpus_iter(), fields=('abstract','title'), meta=('docno','title','abstract'))

16:32:01.374 [ForkJoinPool-2-worker-3] WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (8is9x9sc) - further warnings are suppressed
16:34:06.006 [ForkJoinPool-2-worker-3] WARN org.terrier.structures.indexing.Indexer - Indexed 60 empty documents

> We use pyterrier's `IndexFactory` method to obtain some statistics on the newly created index, such as the number of documents and terms indexed.

In [ ]:
index_factory = pt.IndexFactory.of(index1)
print(index_factory.getCollectionStatistics().toString())

Number of documents: 192509
Number of terms: 158515
Number of postings: 12290426
Number of fields: 2
Number of tokens: 19603234
Field names: [abstract, title]
Positions:   true

### Querying

> The query will be *protein variants*, the scoring function will be **tf-idf**

In [ ]:
query = "protein variants"

In [ ]:
tf_idf_results = pt.BatchRetrieve(index1, wmodel = "TF_IDF", metadata = ["docno", "title", "abstract"]).search(query, )

In [ ]:
tf_idf_results

,qid,docid,docno,title,abstract,rank,score,query
0,1,97334,4nfxdppt,Structural variations in human ACE2 may influe...,"The recent pandemic of COVID-19, caused by SAR...",0,9.645741,protein variants
1,1,153468,m0w0fl2u,Structural variations in human ACE2 may influe...,"The recent pandemic of COVID19, caused by SARS...",1,9.645741,protein variants
2,1,74549,m0xvqplq,"D614G Spike Variant Does Not Alter IgG, IgM, o...",Emergence of a new variant of spike protein (D...,2,9.616081,protein variants
3,1,167441,eb7g9p1x,Localization of extensive deletions in the str...,Abstract The intracellular RNA of two neurotro...,3,9.605184,protein variants
4,1,177319,5pmp33d0,New variants of porcine epidemic diarrhea viru...,Four types of porcine epidemic diarrhea virus ...,4,9.534034,protein variants
...,...,...,...,...,...,...,...,...
995,1,142159,ynown7ra,Outbreak-Related Porcine Epidemic Diarrhea Vir...,"In late 2013, outbreaks of porcine epidemic di...",995,4.551310,protein variants
996,1,167386,y9e5fz3j,Complete Genome Sequence of the Porcine Epidem...,Porcine epidemic diarrhea virus (PEDV) is a ca...,996,4.551310,protein variants
997,1,40784,d14vro73,Interferon lambda 4 genotypes and resistance-a...,UNLABELLED Single-nucleotide polymorphisms (SN...,997,4.550411,protein variants
998,1,602,cjzecgrb,Geometry and Adhesion of Extracellular Domains...,[Image: see text] Forcedistance measurements h...,998,4.538761,protein variants
999,1,62182,ndhwaeci,Emerging role of microRNA 628-5p as a novel bi...,"MicroRNAs are a family of small, single-strand...",999,4.538761,protein variants

> Let's see an example of a results

In [ ]:
tf_idf_results.iloc[2]["title"]

'D614G Spike Variant Does Not Alter IgG, IgM, or IgA Spike Seroassay Performance'

In [ ]:
tf_idf_results.iloc[2]["abstract"]

'Emergence of a new variant of spike protein (D614G) with increased infectivity and transmissibility has prompted many to analyze the potential role of this variant in the SARS-CoV-2 pandemic. When a new variant emerges, there is a concern regarding whether an individual exposed to one variant of a virus will have cross-reactive immune memory to the second variant. Accordingly, we analyzed the serologic reactivity of D614 (original) and G614 variant spike proteins. We found that antibodies from a high-incid'

### Running Experiments
> PyTerrier aims to make it easy to conduct an information retrieval **experiment**, namely, to run a transformer **pipeline** over a set of queries, and evaluating the outcome using standard information retrieval evaluation metrics based on known relevant documents (obtained from a set relevance assessments, also known as qrels).

> The main way to achieve this is using `pt.Experiment()`.

> Let's first define some scoring functions.

> After, we specify that we want to use only the first 10 results.

In [ ]:
CoordinateMatch = pt.BatchRetrieve(index1, wmodel="CoordinateMatch")
TF = pt.BatchRetrieve(index1, wmodel="Tf")
TF_IDF = pt.BatchRetrieve(index1, wmodel="TF_IDF")
LemurTF_IDF = pt.BatchRetrieve(index1, wmodel="LemurTF_IDF")
BM25 = pt.BatchRetrieve(index1, wmodel="BM25")
PL2 = pt.BatchRetrieve(index1, wmodel="PL2")
BM25F = pt.BatchRetrieve(index1, wmodel="BM25F")
PL2F = pt.BatchRetrieve(index1, wmodel="PL2F")

CoordinateMatch_at_10 = CoordinateMatch % 10
TF_at_10 = TF % 10
TF_IDF_at_10 = TF_IDF % 10
LemurTF_IDF_at_10 = LemurTF_IDF % 10
BM25_at_10 = BM25 % 10
PL2_at_10 = PL2 % 10
BM25F_at_10 = BM25F % 10
PL2F_at_10 = PL2F % 10

> Let's also try some **query expansion** techniques.
It is the process of reformulating a given query to improve retrieval performance in information retrieval operations
*   Finding synonyms of words, and searching for the synonyms as well,
*   Finding semantically related words (e.g. antonyms, meronyms, hyponyms, hypernyms),
*   Finding all the various morphological forms of words by stemming each word in the search query,
*   Fixing spelling errors and automatically searching for the corrected form or suggesting it in the results,
*   Re-weighting the terms in the original query,
*   etc...

In [ ]:
sdm = pt.rewrite.SDM()
bo1 = pt.rewrite.Bo1QueryExpansion(index1)
pipeline_1_at_10 = sdm >> TF_IDF % 10
pipeline_2_at_10 = TF_IDF >> bo1 >> TF_IDF % 10

> Extraction of the ground truth as a set of couples <query, relevant_results>.

In [ ]:
topics = dataset.get_topics("title")
qrels = dataset.get_qrels()

[INFO] [starting] https://ir.nist.gov/covidSubmit/data/topics-rnd5.xml
[INFO] [finished] https://ir.nist.gov/covidSubmit/data/topics-rnd5.xml: [00:00] [18.7kB] [7.33MB/s]
[INFO] [starting] https://ir.nist.gov/covidSubmit/data/qrels-covid_d5_j0.5-5.txt
[INFO] [finished] https://ir.nist.gov/covidSubmit/data/qrels-covid_d5_j0.5-5.txt: [00:00] [1.14MB] [3.64MB/s]

Let's see what `topics` and `qrels` look like:

In [ ]:
topics

   qid                                          query
0    1                             coronavirus origin
1    2        coronavirus response to weather changes
2    3                           coronavirus immunity
3    4         how do people die from the coronavirus
4    5                      animal models of covid 19
5    6                 coronavirus test rapid testing
6    7              serological tests for coronavirus
7    8                    coronavirus under reporting
8    9                          coronavirus in canada
9   10           coronavirus social distancing impact
10  11                 coronavirus hospital rationing
11  12                         coronavirus quarantine
12  13                    how does coronavirus spread
13  14                    coronavirus super spreaders
14  15                       coronavirus outside body
15  16  how long does coronavirus survive on surfaces
16  17                    coronavirus clinical trials
17  18                      masks prevent coronavirus
18  19       what alcohol sanitizer kills coronavirus
19  20                 coronavirus and ace inhibitors
20  21                          coronavirus mortality
21  22                      coronavirus heart impacts
22  23                       coronavirus hypertension
23  24                           coronavirus diabetes
24  25                         coronavirus biomarkers
25  26                     coronavirus early symptoms
26  27                       coronavirus asymptomatic
27  28                 coronavirus hydroxychloroquine
28  29                   coronavirus drug repurposing
29  30                         coronavirus remdesivir
30  31         difference between coronavirus and flu
31  32                           coronavirus subtypes
32  33                 coronavirus vaccine candidates
33  34                           coronavirus recovery
34  35                    coronavirus public datasets
35  36                     sars cov 2 spike structure
36  37               sars cov 2 phylogenetic analysis
37  38                    covid inflammatory response
38  39                        covid 19 cytokine storm
39  40                          coronavirus mutations
40  41                  covid 19 in african americans
41  42                         vitamin d and covid 19
42  43                       violence during pandemic
43  44    impact of masks on coronavirus transmission
44  45               coronavirus mental health impact
45  46                      dexamethasone coronavirus
46  47                  covid 19 outcomes in children
47  48                   school reopening coronavirus
48  49               post infection covid 19 immunity
49  50                       mrna vaccine coronavirus

`label` represents the relevance score. It can be binary (0 = not relevant, 1 = relevant) or graded (higher the label, higher the relevance).

In [ ]:
qrels

      qid     docno  label iteration
0       1  005b2j4b      2       4.5
1       1  00fmeepz      1         4
2       1  010vptx3      2       0.5
3       1  0194oljo      1       2.5
4       1  021q9884      1         4
...    ..       ...    ...       ...
69313  50  zvop8bxh      2         5
69314  50  zwf26o63      1         5
69315  50  zwsvlnwe      0         5
69316  50  zxr01yln      1         5
69317  50  zz8wvos9      1         5

[69318 rows x 4 columns]

> Let's run the experiment.

In [ ]:
res_exp_covid = pt.Experiment(
    [CoordinateMatch_at_10, TF_at_10, TF_IDF_at_10, LemurTF_IDF_at_10, BM25_at_10, PL2_at_10, BM25F_at_10, PL2F_at_10, pipeline_1_at_10, pipeline_2_at_10],
    topics,
    qrels,
    eval_metrics=["P_1", "P_3", "ndcg_cut_3", "P_5", "ndcg_cut_5", "P_10", "ndcg_cut_10", "num_q"],
    #round={"P_1":2, "P_3":2, "P_5":2, "P_10":2, "ndcg_cut_3":2, "ndcg_cut_5":2, "ndcg_cut_10":2, "num_q":0},
    names=["CoordinateMatch_at_10", "TF_at_10", "TF_IDF_at_10", "LemurTF_IDF_at_10", "BM25_at_10", "PL2_at_10", "BM25F_at_10", "PL2F_at_10", "pipeline_1_at_10", "pipeline_2_at_10"],
    highlight="bold"
)

#YOUR TURN: Try different evaluation metrics

In [ ]:
res_exp_covid

### Let's test another dataset.

> We use a subset of the **wikipedia** dataset

> We follow the same procedure as above to download the dataset and create the index

In [ ]:
wiki_dataset_name = 'irds:wikir/en1k/test'

wiki_dataset = pt.get_dataset(wiki_dataset_name) #download dataset

#YOUR TURN: Try to use a different PyTerrier dataset (!!!Not every dataset has queries' relevance scores!!!)

In [ ]:
folder_pos = './indices/wikir_en1k'
!rm -r $folder_pos #remove index if already created

rm: cannot remove './indices/wikir_en1k': No such file or directory

In [ ]:
indexer = pt.IterDictIndexer(folder_pos,  meta_reverse=[], blocks=True)
index2 = indexer.index(wiki_dataset.get_corpus_iter(), fields=['text'])

wikir/en1k/test documents:   0%|          | 0/369721 [00:00<?, ?it/s]

[INFO] If you have a local copy of https://zenodo.org/record/3565761/files/wikIR1k.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/554299bca984640cb283d6ba55753608
[INFO] [starting] https://zenodo.org/record/3565761/files/wikIR1k.zip

https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.0%| 0.00/165M [00:00<?, ?B/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.0%| 32.8k/165M [00:00<12:16, 224kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.0%| 81.9k/165M [00:00<10:09, 271kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.1%| 131k/165M [00:00<09:38, 285kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.1%| 197k/165M [00:00<08:37, 318kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.2%| 262k/165M [00:00<08:06, 338kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.2%| 328k/165M [00:00<07:48, 352kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.2%| 393k/165M [00:01<07:36, 361kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.3%| 459k/165M [00:01<07:27, 368kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.3%| 524k/165M [00:01<07:20, 373kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.4%| 590k/165M [00:01<07:15, 378kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.4%| 655k/165M [00:01<07:11, 381kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.4%| 721k/165M [00:01<07:07, 384kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.5%| 786k/165M [00:02<07:04, 387kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.5%| 868k/165M [00:02<06:54, 396kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.6%| 950k/165M [00:02<06:45, 404kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.6%| 1.03M/165M [00:02<06:39, 411kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.7%| 1.11M/165M [00:02<06:33, 417kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.7%| 1.20M/165M [00:02<06:48, 401kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.8%| 1.28M/165M [00:03<06:42, 407kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.8%| 1.36M/165M [00:03<06:37, 412kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.9%| 1.44M/165M [00:03<06:32, 417kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 0.9%| 1.52M/165M [00:03<06:44, 404kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.0%| 1.61M/165M [00:03<06:39, 409kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.0%| 1.69M/165M [00:04<06:35, 413kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.1%| 1.77M/165M [00:04<06:32, 416kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.1%| 1.85M/165M [00:04<06:41, 406kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.2%| 1.93M/165M [00:04<06:38, 410kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.2%| 2.02M/165M [00:04<06:35, 412kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.3%| 2.10M/165M [00:05<06:32, 415kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.3%| 2.18M/165M [00:05<06:39, 407kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.4%| 2.26M/165M [00:05<06:36, 410kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.4%| 2.34M/165M [00:05<06:34, 413kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.5%| 2.42M/165M [00:05<06:31, 415kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.5%| 2.51M/165M [00:06<06:38, 408kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.6%| 2.59M/165M [00:06<06:35, 410kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.6%| 2.67M/165M [00:06<06:33, 412kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.7%| 2.75M/165M [00:06<06:30, 415kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.7%| 2.83M/165M [00:06<06:37, 408kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.8%| 2.92M/165M [00:07<06:34, 411kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.8%| 3.00M/165M [00:07<06:32, 413kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.9%| 3.08M/165M [00:07<06:37, 407kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 1.9%| 3.16M/165M [00:07<06:35, 409kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.0%| 3.24M/165M [00:07<06:33, 411kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.0%| 3.33M/165M [00:08<06:31, 413kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.1%| 3.41M/165M [00:08<06:36, 408kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.2%| 3.60M/165M [00:08<06:21, 423kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.3%| 3.80M/165M [00:08<06:15, 430kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.4%| 4.00M/165M [00:09<06:15, 429kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.5%| 4.19M/165M [00:09<06:15, 428kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.7%| 4.39M/165M [00:10<06:09, 434kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.8%| 4.59M/165M [00:10<06:09, 434kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 2.9%| 4.78M/165M [00:10<06:04, 439kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 3.0%| 4.98M/165M [00:11<06:05, 438kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 3.1%| 5.18M/165M [00:11<06:00, 443kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 3.3%| 5.37M/165M [00:12<06:01, 442kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 3.4%| 5.57M/165M [00:12<05:57, 446kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 3.5%| 5.77M/165M [00:12<05:58, 444kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 3.6%| 5.96M/165M [00:13<05:58, 443kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 3.7%| 6.16M/165M [00:13<05:59, 442kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 3.9%| 6.36M/165M [00:14<05:56, 445kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.0%| 6.55M/165M [00:14<05:56, 444kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.1%| 6.75M/165M [00:15<05:57, 443kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.2%| 6.95M/165M [00:15<05:54, 446kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.3%| 7.14M/165M [00:16<05:54, 445kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.4%| 7.34M/165M [00:16<05:54, 444kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.6%| 7.54M/165M [00:16<05:51, 448kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.7%| 7.73M/165M [00:17<05:51, 447kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.8%| 7.93M/165M [00:17<05:52, 446kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 4.9%| 8.13M/165M [00:18<05:49, 449kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 5.0%| 8.32M/165M [00:18<05:46, 452kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 5.2%| 8.52M/165M [00:18<05:46, 451kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 5.3%| 8.72M/165M [00:19<05:47, 450kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 5.4%| 8.91M/165M [00:19<05:44, 453kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 5.5%| 9.11M/165M [00:20<05:44, 452kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 5.6%| 9.31M/165M [00:20<05:42, 455kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 5.8%| 9.50M/165M [00:20<05:40, 457kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 5.9%| 9.70M/165M [00:21<05:40, 456kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 6.0%| 9.90M/165M [00:21<05:38, 459kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 6.1%| 10.1M/165M [00:22<05:38, 458kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 6.2%| 10.3M/165M [00:22<05:38, 457kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 6.4%| 10.5M/165M [00:22<05:36, 459kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 6.5%| 10.7M/165M [00:23<05:34, 462kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 6.6%| 10.9M/165M [00:23<05:34, 461kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 6.7%| 11.1M/165M [00:23<05:32, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 6.8%| 11.3M/165M [00:24<05:32, 462kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.0%| 11.5M/165M [00:24<05:32, 461kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.1%| 11.7M/165M [00:25<05:31, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.2%| 11.9M/165M [00:25<05:31, 462kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.3%| 12.1M/165M [00:25<05:29, 464kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.4%| 12.3M/165M [00:26<05:29, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.5%| 12.5M/165M [00:26<05:29, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.7%| 12.6M/165M [00:27<05:29, 462kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.8%| 12.8M/165M [00:27<05:28, 464kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 7.9%| 13.0M/165M [00:28<05:28, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 8.0%| 13.2M/165M [00:28<05:26, 465kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 8.1%| 13.4M/165M [00:28<05:26, 464kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 8.3%| 13.6M/165M [00:29<05:25, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 8.4%| 13.8M/165M [00:29<05:25, 465kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 8.5%| 14.0M/165M [00:30<05:25, 464kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 8.6%| 14.2M/165M [00:30<05:25, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 8.7%| 14.4M/165M [00:31<05:25, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 8.9%| 14.6M/165M [00:31<05:25, 462kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.0%| 14.8M/165M [00:31<05:24, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.1%| 15.0M/165M [00:32<05:24, 463kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.2%| 15.2M/165M [00:32<05:22, 464kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.3%| 15.4M/165M [00:33<05:21, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.5%| 15.6M/165M [00:33<05:21, 465kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.6%| 15.8M/165M [00:34<05:21, 464kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.7%| 16.0M/165M [00:34<05:19, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.8%| 16.2M/165M [00:34<05:19, 465kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 9.9%| 16.4M/165M [00:35<05:18, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 10.0%| 16.6M/165M [00:35<05:18, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 10.2%| 16.8M/165M [00:36<05:18, 465kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 10.3%| 17.0M/165M [00:36<05:18, 464kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 10.4%| 17.2M/165M [00:36<05:17, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 10.5%| 17.4M/165M [00:37<05:17, 465kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 10.6%| 17.6M/165M [00:37<05:17, 464kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 10.8%| 17.8M/165M [00:38<05:16, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 10.9%| 18.0M/165M [00:38<05:16, 465kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 11.0%| 18.2M/165M [00:38<05:14, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 11.1%| 18.4M/165M [00:39<05:14, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 11.2%| 18.5M/165M [00:39<05:13, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 11.4%| 18.7M/165M [00:40<05:12, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 11.5%| 18.9M/165M [00:40<05:12, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 11.6%| 19.1M/165M [00:40<05:11, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 11.7%| 19.3M/165M [00:41<05:11, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 11.8%| 19.5M/165M [00:41<05:11, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.0%| 19.7M/165M [00:42<05:10, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.1%| 19.9M/165M [00:42<05:10, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.2%| 20.1M/165M [00:42<05:09, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.3%| 20.3M/165M [00:43<05:09, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.4%| 20.5M/165M [00:43<05:09, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.6%| 20.7M/165M [00:44<05:09, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.7%| 20.9M/165M [00:44<05:09, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.8%| 21.1M/165M [00:45<05:09, 465kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 12.9%| 21.3M/165M [00:45<05:08, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 13.0%| 21.5M/165M [00:46<05:08, 466kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 13.1%| 21.7M/165M [00:46<05:07, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 13.3%| 21.9M/165M [00:46<05:05, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 13.4%| 22.1M/165M [00:47<05:05, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 13.5%| 22.3M/165M [00:47<05:05, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 13.6%| 22.5M/165M [00:48<05:04, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 13.7%| 22.7M/165M [00:48<05:03, 469kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 13.9%| 22.9M/165M [00:48<05:03, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.0%| 23.1M/165M [00:49<05:03, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.1%| 23.3M/165M [00:49<05:03, 467kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.2%| 23.5M/165M [00:50<05:02, 468kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.3%| 23.7M/165M [00:50<05:01, 469kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.5%| 23.9M/165M [00:50<05:01, 469kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.6%| 24.1M/165M [00:51<05:00, 470kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.7%| 24.2M/165M [00:51<05:00, 469kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.8%| 24.4M/165M [00:52<04:59, 470kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 14.9%| 24.6M/165M [00:52<04:59, 469kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 15.1%| 24.8M/165M [00:52<04:57, 470kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 15.2%| 25.0M/165M [00:53<04:57, 471kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 15.3%| 25.2M/165M [00:53<04:56, 471kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 15.4%| 25.4M/165M [00:53<04:55, 472kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 15.5%| 25.6M/165M [00:54<04:55, 471kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 15.6%| 25.8M/165M [00:54<04:54, 472kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 15.8%| 26.0M/165M [00:55<04:54, 472kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 15.9%| 26.2M/165M [00:55<04:53, 472kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 16.0%| 26.4M/165M [00:55<04:53, 472kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 16.1%| 26.6M/165M [00:56<04:52, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 16.2%| 26.8M/165M [00:56<04:52, 472kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 16.4%| 27.0M/165M [00:57<04:52, 472kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 16.5%| 27.2M/165M [00:57<04:51, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 16.6%| 27.4M/165M [00:58<04:51, 472kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 16.7%| 27.6M/165M [00:58<04:50, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 16.8%| 27.8M/165M [00:58<04:50, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.0%| 28.0M/165M [00:59<04:49, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.1%| 28.2M/165M [00:59<04:49, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.2%| 28.4M/165M [00:59<04:48, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.3%| 28.6M/165M [01:00<04:48, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.4%| 28.8M/165M [01:00<04:47, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.6%| 29.0M/165M [01:01<04:47, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.7%| 29.2M/165M [01:01<04:47, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.8%| 29.4M/165M [01:01<04:46, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 17.9%| 29.6M/165M [01:02<04:45, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 18.0%| 29.8M/165M [01:02<04:45, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 18.2%| 29.9M/165M [01:03<04:44, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 18.3%| 30.1M/165M [01:03<04:44, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 18.4%| 30.3M/165M [01:03<04:43, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 18.5%| 30.5M/165M [01:04<04:44, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 18.6%| 30.7M/165M [01:04<04:43, 473kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 18.7%| 30.9M/165M [01:05<04:42, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 18.9%| 31.1M/165M [01:05<04:42, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 19.0%| 31.3M/165M [01:06<04:41, 475kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 19.1%| 31.5M/165M [01:06<04:41, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 19.2%| 31.7M/165M [01:06<04:41, 474kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 19.5%| 32.1M/165M [01:07<04:37, 478kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 20.0%| 33.0M/165M [01:07<04:29, 490kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 21.0%| 34.7M/165M [01:07<04:13, 514kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 22.4%| 36.9M/165M [01:07<03:54, 546kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 23.7%| 39.2M/165M [01:08<03:38, 575kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 25.1%| 41.4M/165M [01:08<03:24, 603kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 26.5%| 43.7M/165M [01:09<03:12, 630kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 27.9%| 46.0M/165M [01:09<03:01, 657kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 29.2%| 48.2M/165M [01:10<02:51, 682kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 30.6%| 50.5M/165M [01:11<02:41, 708kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 32.0%| 52.7M/165M [01:12<02:33, 732kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 33.3%| 55.0M/165M [01:12<02:25, 757kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 34.7%| 57.3M/165M [01:13<02:17, 782kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 36.1%| 59.5M/165M [01:13<02:11, 805kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 37.4%| 61.8M/165M [01:14<02:04, 827kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 38.8%| 64.0M/165M [01:15<01:58, 851kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 40.2%| 66.3M/165M [01:15<01:53, 873kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 41.6%| 68.6M/165M [01:16<01:47, 896kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 42.9%| 70.8M/165M [01:17<01:42, 917kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 44.3%| 73.1M/165M [01:17<01:37, 939kB/s]
https://zenodo.org/record/3565761/files/wikIR1k.zip: 45.7%| 75.4M/165M [01:18<01:33, 960kB/s]

> Let's see some statistics on this new index

In [ ]:
index_factory = pt.IndexFactory.of(index2)
print(index_factory.getCollectionStatistics().toString())

Number of documents: 369721
Number of terms: 674552
Number of postings: 30552936
Number of fields: 1
Number of tokens: 41306796
Field names: [text]
Positions:   true

> We set up the same experiment on the Covid dataset to highlight the differences with the previous case.

In [ ]:
CoordinateMatch = pt.BatchRetrieve(index2, wmodel="CoordinateMatch")
TF = pt.BatchRetrieve(index2, wmodel="Tf")
TF_IDF = pt.BatchRetrieve(index2, wmodel="TF_IDF")
LemurTF_IDF = pt.BatchRetrieve(index2, wmodel="LemurTF_IDF")
BM25 = pt.BatchRetrieve(index2, wmodel="BM25")
PL2 = pt.BatchRetrieve(index2, wmodel="PL2")

CoordinateMatch_at_10 = CoordinateMatch % 10
TF_at_10 = TF % 10
TF_IDF_at_10 = TF_IDF % 10
LemurTF_IDF_at_10 = LemurTF_IDF % 10
BM25_at_10 = BM25 % 10
PL2_at_10 = PL2 % 10

In [ ]:
sdm = pt.rewrite.SDM()
bo1 = pt.rewrite.Bo1QueryExpansion(index2)
pipeline_1_at_10 = sdm >> TF_IDF % 10
pipeline_2_at_10 = TF_IDF >> bo1 >> TF_IDF % 10
pipeline_3_at_10 = sdm >> BM25 % 10
pipeline_4_at_10 = BM25 >> bo1 >> BM25 % 10

In [ ]:
topics = wiki_dataset.get_topics()
qrels = wiki_dataset.get_qrels()

> Let's run the experiment

In [ ]:
res_exp_wiki_dataset = pt.Experiment(
    [CoordinateMatch_at_10, TF_at_10, TF_IDF_at_10, LemurTF_IDF_at_10, BM25_at_10, PL2_at_10, pipeline_1_at_10, pipeline_2_at_10, pipeline_3_at_10, pipeline_4_at_10],
    topics,
    qrels,
    eval_metrics=["P_1", "P_3", "ndcg_cut_3", "P_5", "ndcg_cut_5", "P_10", "ndcg_cut_10", "num_q"],
    #round={"P_1":2, "P_3":2, "P_5":2, "P_10":2, "ndcg_cut_3":2, "ndcg_cut_5":2, "ndcg_cut_10":2, "num_q":0},
    names=["CoordinateMatch_at_10", "TF_at_10", "TF_IDF_at_10", "LemurTF_IDF_at_10", "BM25_at_10", "PL2_at_10", "pipeline_1_at_10", "pipeline_2_at_10","pipeline_3_at_10", "pipeline_4_at_10"],
    highlight="bold"
)

In [ ]:
res_exp_wiki_dataset

> We can see that there is not always one method that prevails over the others, but it often depends on the metrics taken into consideration.